#!/usr/bin/env bash
#
# compose-env-example.sh — keep a committed .env.example next to every Docker
#   Compose stack, listing the environment variables that stack's compose file
#   references, with values BLANK (or the compose-provided default).
#
# Why: real .env files are gitignored, so a repo with no template can't be
#   rebuilt without tribal knowledge. This makes the contract explicit and
#   diffable, and CI can fail when it drifts.
#
# Usage:
#   ./compose-env-example.sh [-d DIR] [-w | -c]
#
# Options:
#   -d DIR   Directory to scan for compose files (default: current directory).
#   -w       Write/update the .env.example files (default action).
#   -c       Check only: exit 1 if any .env.example is missing or stale.
#   -h       Show this help.
#
# Safety: values are taken ONLY from `${VAR:-default}` in the compose file.
#   Real .env files are read for KEY NAMES ONLY (to catch keys injected via
#   `env_file:` that never appear as ${VAR}); their values are never read.
#
# Exit codes: 0 = OK / in sync, 1 = drift found (check mode), 2 = usage/other error

set -uo pipefail

DIR="."
MODE="write"

usage() { grep -E "^#( |$)" "$0" | sed "1d;s/^#\\s\\?//"; exit "${1:-0}"; }

while getopts ":d:wch" opt; do
  case "$opt" in
    d) DIR="$OPTARG" ;;
    w) MODE="write" ;;
    c) MODE="check" ;;
    h) usage 0 ;;
    \?) echo "Unknown option: -$OPTARG" >&2; usage 2 ;;
    :) echo "Option -$OPTARG requires an argument" >&2; usage 2 ;;
  esac
done

[ -d "$DIR" ] || { echo "Not a directory: $DIR" >&2; exit 2; }
cd "$DIR" || exit 2

mapfile -t COMPOSE < <(find . -type f \( -name 'compose.yml' -o -name 'compose.yaml' \
  -o -name 'docker-compose.yml' -o -name 'docker-compose.yaml' \) | sort)

if [ "${#COMPOSE[@]}" -eq 0 ]; then
  echo "No compose files found under $DIR" >&2
  exit 2
fi

env_file_targets() {  # $1 = compose file -> prints referenced env_file paths
  awk '
    /^[[:space:]]*env_file:[[:space:]]*\[/ {
      s = $0; sub(/.*\[/, "", s); sub(/\].*/, "", s)
      n = split(s, a, ",")
      for (i = 1; i <= n; i++) { gsub(/[[:space:]"'"'"']/, "", a[i]); if (a[i] != "") print a[i] }
      next
    }
    /^[[:space:]]*env_file:[[:space:]]*[^[:space:]#]/ { v = $2; gsub(/["'"'"']/, "", v); print v; next }
    /^[[:space:]]*env_file:[[:space:]]*$/ { blk = 1; next }
    blk && /^[[:space:]]*-[[:space:]]*/ { v = $2; gsub(/["'"'"']/, "", v); print v; next }
    blk { blk = 0 }
  ' "$1"
}

drift=0
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

for f in "${COMPOSE[@]}"; do
  d="$(dirname "$f")"
  stack="$(basename "$d")"
  [ "$d" = "." ] && stack="$(basename "$PWD")"

  declare -A KV

  # ${VAR} / ${VAR:-default} / ${VAR:?} / ${VAR-default}
  while IFS= read -r tok; do
    name="${tok#\$\{}"; name="${name%\}}"
    case "$name" in
      *:-*)  def="${name#*:-}";  name="${name%%:-*}"  ;;
      *:\?*) def="";             name="${name%%:\?*}" ;;
      *:+*)  def="";             name="${name%%:+*}"  ;;
      *-*)   def="${name#*-}";   name="${name%%-*}"   ;;
      *)     def=""                                   ;;
    esac
    [[ "$name" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
    if [ -z "${KV[$name]+set}" ]; then
      KV["$name"]="$def"
    elif [ -z "${KV[$name]}" ] && [ -n "$def" ]; then
      KV["$name"]="$def"
    fi
  done < <(grep -oE '\$\{[A-Za-z_][A-Za-z0-9_]*(:?[-?+][^}]*)?\}' "$f" || true)

  # names injected via env_file: (names only, never values)
  while IFS= read -r ef; do
    [ -n "$ef" ] || continue
    [ -f "$d/$ef" ] || continue
    while IFS= read -r k; do
      [ -z "${KV[$k]+set}" ] && KV["$k"]=""
    done < <(sed -nE 's/^[[:space:]]*([A-Za-z_][A-Za-z0-9_]*)=.*/\1/p' "$d/$ef")
  done < <(env_file_targets "$f")

  [ "${#KV[@]}" -eq 0 ] && { unset KV; continue; }

  out="$tmp/env.example"
  {
    echo "# $stack — environment variables referenced by $(basename "$f")."
    echo "# Generated by compose-env-example.sh. Put REAL values in $d/.env (gitignored)."
    echo
    while IFS= read -r k; do
      printf '%s=%s\n' "$k" "${KV[$k]}"
    done < <(printf '%s\n' "${!KV[@]}" | LC_ALL=C sort)
  } > "$out"

  live="$d/.env.example"
  if [ "$MODE" = check ]; then
    if ! diff -q "$live" "$out" >/dev/null 2>&1; then
      echo "DRIFT: $live"
      diff -u "$live" "$out" 2>/dev/null | sed 's/^/    /'
      drift=1
    fi
  else
    if ! diff -q "$live" "$out" >/dev/null 2>&1; then
      cp "$out" "$live"
      echo "updated $live (${#KV[@]} keys)"
    else
      echo "ok      $live"
    fi
  fi

  unset KV
done

if [ "$MODE" = check ] && [ "$drift" -ne 0 ]; then
  echo
  echo "Run without -c to regenerate, then commit." >&2
  exit 1
fi
exit 0
